export const UPDATE_GROUPS = "UPDATE_GROUPS";

export const REQUEST_SOMETHING_PENDING = "REQUEST_SOMETHING_PENDING";
export const REQUEST_SOMETHING_SUCCESS = "REQUEST_SOMETHING_SUCCESS";
export const REQUEST_SOMETHING_FAILED = "REQUEST_SOMETHING_FAILED";
